name: CI
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Clean Install
        run: npm ci
      - name: Unit Test
        run: npm run test
      - name: Build Distribution
        run: npm run build
      - name: Release
        if: github.ref == 'refs/heads/master'
        run: npx semantic-release@19.0.5 --branches master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
